name: ResonosHeadsteal
version: '1.0-SNAPSHOT'
main: studio.resonos.headsteal.ResonosHeadsteal
author: oShifuu
website: https://discord.gg/wdKJW5gBFC
api-version: '1.20'
#LPC Is Luckperms chat formatting plugin
depend:
  - LuckPerms
  - LPC
